name: Update data
    
on:
  schedule:
    - cron: "0 22 * * *" #runs at 22:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update the file count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if run.py requires passwords..etc, set it as secrets
        run: |
          python query_api.py
          python plot.py
          cat current_count.txt
